spring:
  application:
    name: springboot-sharding-jdbc
  datasource:
    username: root
    password: Password01!
    url: jdbc:mysql://localhost:3306/dancechar
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8012
