spring:
  application:
    name: base-mybatis-generator
  datasource:
    username: root
    password: Password01!
    url: jdbc:mysql://localhost:3306/springboot_db
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8012
